services:
  - type: web
    name: inventory-api
    env: node
    region: oregon
    plan: free
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    autoDeploy: true

    envVars:
      - key: NODE_ENV
        value: production

      - key: PORT
        value: 3002

      # üîπ Base de datos (Render)
      - key: DATABASE_URL
        fromDatabase:
          name: inventory-db
          property: connectionString

      # üîê Auth
      - key: JWT_SECRET
        sync: false

      - key: JWT_REFRESH_SECRET
        sync: false

      # ‚òÅÔ∏è Cloudinary
      - key: CLOUDINARY_API_KEY
        sync: false

      - key: CLOUDINARY_API_SECRET
        sync: false

      - key: CLOUDINARY_CLOUD_NAME
        sync: false

databases:
  - name: inventory-db
    plan: free
    region: oregon
    postgresMajorVersion: 15
